minimum_pre_commit_version: "2.10.0"
exclude: >
  (?x)^(
    .*\.svg
  )$
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.0
    hooks:
      - id: ruff
        args:
          - --fix
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        name: isort (python)
        args:
          - --dont-order-by-type
  - repo: https://github.com/psf/black
    rev: "24.1.1"
    hooks:
      - id: black
        name: Format code (black)
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.5.0"
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
      - id: check-toml
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v1.8.0"
    hooks:
      - id: "mypy"
        name: "Check type hints (mypy)"
        verbose: true
        additional_dependencies:
          - types-python-slugify
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly
  skip: []
  submodules: false
