minimum_pre_commit_version: "3.0.4"
exclude: >
  (?x)^(
    .*\.svg
  )$
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v4.6.0"
    hooks:
      - id: "end-of-file-fixer"
      - id: "trailing-whitespace"
      - id: "check-json"
      - id: "check-toml"
      - id: "check-yaml"

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        types_or: [css, yaml, markdown, json]
  - repo: "https://github.com/pre-commit/mirrors-mypy"
    rev: "v1.10.1"
    hooks:
      - id: "mypy"
        name: "Check type hints (mypy)"
        verbose: true
        additional_dependencies:
          - types-python-slugify
          - types-PyYAML
          - pydantic
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: monthly
  skip: []
  submodules: false
